### ISSUE TITLE
I need your help please 

### ISSUE THREAD

**Issue by 1151kareem** [pandzel/RobotsTxt#5]
hi can you please help me 

this is my code 

			 InputStream robotsTxtStream = null;
			try {
				robotsTxtStream = new URL("https://github.com/robots.txt").openStream();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} 
				  
					RobotsTxt robotsTxt;
					try {
						robotsTxt = RobotsTxt.read(robotsTxtStream);
						boolean hasAccess = robotsTxt.query(null,"/humans.txt");
					} catch (IOException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
					

and this is the error I keep getting

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
	at com.panforge.robotstxt.RobotsTxtReader.parseEntry(RobotsTxtReader.java:157)
	at com.panforge.robotstxt.RobotsTxtReader.readEntry(RobotsTxtReader.java:139)
	at com.panforge.robotstxt.RobotsTxtReader.readRobotsTxt(RobotsTxtReader.java:64)
	at com.panforge.robotstxt.RobotsTxt.read(RobotsTxt.java:72)
	at asdasd.main(asdasd.java:28)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.StringUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more

**Comment by pandzel** [comment]
This error indicates that you are missing dependency (a *.jar file) on your classpath. Most precisely, https://commons.apache.org/proper/commons-lang/ jar file is missing. It really depends how you build and distribute your application.

**Comment by 1151kareem** [comment]
thank you so much I fixed it
